module RailsAuditLog
  module Graphql
    VERSION: String

    module Types
      class BaseObject < GraphQL::Schema::Object
      end

      class AuditLogEntryType < BaseObject
      end
    end

    module Generators
      module Graphql
        class InstallGenerator < ::Rails::Generators::Base
          def inject_mixin: () -> void
          def print_next_steps: () -> void
        end
      end
    end

    module Queries
      module AuditLogEntriesQueryMixin
        def self.included: (untyped base) -> void
        def resolve_audit_log_entry: (id: String) -> untyped
        def resolve_audit_log_entries: (?event: String?, ?item_type: String?, ?item_id: String?, ?actor_id: String?, ?page: Integer, ?per_page: Integer) -> untyped
        private
        def check_authentication!: () -> void
      end
    end
  end
end
